# finetune_cyrillic_ocr_v3.yml

_base_:
  - ./multi_language/cyrillic_PP-OCRv3_mobile_rec.yml

Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform:
  Backbone:
    name: MobileNetV1Enhance
    scale: 0.5
    last_conv_stride: [1, 2]
    last_pool_type: avg
    last_pool_kernel_size: [2, 2]
  Head:
    name: MultiHead
    head_list:
      - CTCHead:
          Neck:
            name: svtr
            dims: 64
            depth: 2
            hidden_dims: 120
            use_guide: True
          Head:
            fc_decay: 0.00001
      - SARHead:
          enc_dim: 512
          max_text_length: 25

Loss:
  name: MultiLoss
  loss_config_list:
    - CTCLoss:
    - SARLoss:

PostProcess:  
  name: CTCLabelDecode

Metric:
  name: RecMetric
  main_indicator: acc
  ignore_space: False

Global:
  pretrained_model: ./pretrain_models/ru_PP-OCRv3_rec_train/best_accuracy
  save_model_dir: ./output/cyrillic_tuned_recognizer/
  character_dict_path: ppocr/utils/dict/cyrillic_dict.txt
  epoch_num: 100
  eval_batch_step: [0, 200]

# --- ПОЛНАЯ И ИСПРАВЛЕННАЯ СЕКЦИЯ OPTIMIZER ---
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.0001
  regularizer:
    name: L2
    factor: 3.0e-05

Train:
  dataset:
    name: SimpleDataSet
    data_dir: ../ocr_pipeline_project/data/processed/
    label_file_list: ["../ocr_pipeline_project/data/processed/train_labels.txt"]
    transforms:
    - DecodeImage: {img_mode: BGR, channel_first: false}
    - RecConAug: {prob: 0.5, ext_data_num: 2, image_shape: [48, 320, 3]}
    - RecAug:
    - MultiLabelEncode: {max_text_length: 25}
    - RecResizeImg: {image_shape: [3, 48, 320]}
    - KeepKeys: {keep_keys: ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']}
  loader:
    shuffle: true
    drop_last: true 
    batch_size_per_card: 3
    num_workers: 4
  
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ../ocr_pipeline_project/data/processed/
    label_file_list: ["../ocr_pipeline_project/data/processed/eval_labels.txt"]
    transforms:
    - DecodeImage: {img_mode: BGR, channel_first: false}
    - MultiLabelEncode: {max_text_length: 25}
    - RecResizeImg: {image_shape: [3, 48, 320]}
    - KeepKeys: {keep_keys: ['image', 'label_ctc', 'label_sar', 'length', 'valid_ratio']}
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 3
    num_workers: 4